services:
  mongo:
    image: mongo:7.0
    container_name: mongoDB
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - stock-net

  backend:
    image: stock-backend:local
    container_name: stock-backend
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/stockDB
      TIMING_SERVICE_URL: http://stock-ai-api:5000/evaluate
    ports:
      - "8080:8080"
    networks:
      - stock-net

  ai_api:
    image: stock-ai-api:local
    container_name: stock-ai-api
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/stockDB
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    networks:
      - stock-net

volumes:
  mongo_data:

networks:
  stock-net:
    external: true
    name: stock-net
