apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stock-web
  namespace: stock
spec:
  ingressClassName: nginx
  rules:
    - host: stock.localdev.me
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-svc
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stock-ai
  namespace: stock
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: stock.localdev.me
      http:
        paths:
          - path: /ai(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ai-api-svc
                port:
                  number: 5000
