# ????
spring.application.name=stock-backend

# MongoDB ??
spring.data.mongodb.uri=mongodb://localhost:27017/stockDB
spring.data.mongodb.database=stockDB

# ??????? React localhost:3000?
spring.web.allow-cors=true

timing.service.url=${TIMING_SERVICE_URL:http://localhost:5000/evaluate}
